---
- hosts: localhost
  connection: local
  user: zero
  become: yes
  pre_tasks:
  - name: Pretask | Update apt cache
    apt: update_cache=yes
  roles:
    - common
    - package-mgmt
    - shell-settings
    - shell-tools
    - local-storage
    - desktop-kit
    - desktop-fingerprint
    - desktop-teamviewer
    - desktop-anydesk
    - desktop-google-chrome
    - desktop-insync
    - desktop-zoom
    - desktop-slack
    - desktop-brave-browser 
    - desktop-telegram
    - github-service

