---
- hosts: localhost
  connection: local
  user: jmedina
  become: yes
  pre_tasks:
  - name: Pretask | Update apt cache
    apt: update_cache=yes
  roles:
    - common
    - package-mgmt
    - shell-settings
    - shell-tools
    - local-storage
    - desktop-kit
    - desktop-insync
    - desktop-teamviewer
    - desktop-skype
    - desktop-slack
    - desktop-zoom
#    - desktop-google-chrome
#    - desktop-fingerprint
#    - desktop-flux
