---
- hosts: localhost
  connection: local
  user: jmedina
  become: yes
  pre_tasks:
  - name: Pretask | Update apt cache
    apt: update_cache=yes
  roles:
    - common
    - package-mgmt
    - shell-settings
    - shell-tools
    - local-storage
    - desktop-kit
    - desktop-oh-my-zsh
    - desktop-teamviewer
    - desktop-google-chrome
    - desktop-insync
    #- desktop-flux
    #- desktop-fingerprint
    #- desktop-skype
    #- desktop-slack
    #- desktop-zoom
 
