---
# tasks file for desktop-insync

- name: Configure Insync's repository APT key
  apt_key: keyserver=keyserver.ubuntu.com id=ACCAF35C state=present
  tags:
    - desktop_insync

- name: Add Insync Ubuntu Repository to keychain
  apt_repository: repo='deb http://apt.insynchq.com/ubuntu {{ ansible_distribution_release }} non-free contrib' state=present
  tags:
    - desktop_insync

- name: Update apt cache so we load Insync repository
  apt: update_cache=yes
  tags:
    - desktop_insync

- name: Install Insync desktop package
  apt: pkg={{ item }} state=latest
  with_items:
    - insync
  tags:
    - desktop_insync
