---
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - cron
      - gnupg2
      - curl
      - aufs-tools
    state: present

- name: Get Docker key
  apt_key:
    url: "{{ docker_repo_key }}"
    state: present

- name: Add Docker repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
    state: present
    update_cache: yes

- name: Install Docker CE, python-docker & Docker Compose
  apt:
    name:
      - docker-ce
      - python-docker
      - docker-compose
    state: present

- name: Add admin user to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
