---
# tasks file for desktop-brave-browser

- name: Install Dependencies
  apt:
    name:
      - apt-transport-https
  tags:
    - desktop_brave_browser

- name: Configure Brave APT key
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  tags:
    - desktop_brave_browser

- name: Add Brave repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com stable main
    filename: brave-browser-release
    state: present
  tags:
    - desktop_brave_browser
 
- name: Install Brave Browser
  apt:
    name: brave-browser
  tags:
    - desktop_brave_browser

