---
galaxy_info:
  author: Jorge Medina
  description: Tasks for setting up aws cli via pip.
  company: KronOps
  license: MIT
  min_ansible_version: 2.4
  platforms:
  - name: Ubuntu
    versions:
    - focal
  categories:
  - development
dependencies: []
