---
# tasks file for desktop-virtualbox

- name: Install virtualbox build-esential and dkms dependencies
  apt:
    name:
      - build-essential
      - dkms
      - unzip
    state: latest
  tags:
    - desktop_virtualbox

- name: Configure the Oracle 2016 APT key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc state=present
  tags:
    - desktop_virtualbox

- name: Configure the Oracle APT key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc state=present
  tags:
    - desktop_virtualbox

- name: Configure the VirtualBox APT repositories
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib" state=present
  tags:
    - desktop_virtualbox

- name: Receive and add key from virtualbox
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A2F683C52980AECF
  tags:
    - desktop_virtualbox

- name: Update apt cache
  apt: update_cache=yes
  tags:
    - desktop_virtualbox

- name: Install VirtualBox and friends
  apt:
    name:
      - virtualbox-{{ virtualbox_version }}
      - virtualbox-dkms
    state: present
  tags:
    - desktop_virtualbox

- name: Add user jmedina to virtualbox group
  user: name={{ ansible_user_id }} groups=vboxusers append=yes
  tags:
    - desktop_virtualbox

