---
galaxy_info:
  author: Jorge Medina
  description: Deploy oh my zsh on ubuntu desktop.
  company: KronOps
  license: MIT
  min_ansible_version: 2.8
  platforms:
  - name: Ubuntu
    versions:
    - focal
  categories:
  - destkop
dependencies: []
