---
# defaults file for role

aws_cli_user: 'jmedina'
aws_cli_group: 'jmedina'
aws_cli_user_home: '/home/jmedina'
aws_output_format: 'json'
aws_region: 'us-west-2'
aws_access_key_id: 'YOUR_ACCESS_KEY_ID'
aws_secret_access_key: 'YOUR_SECRET_ACCESS_KEY'
