---
# tasks file for desktop-zoom

- name: Download zoom package
  get_url:
    url: https://zoom.us/client/latest/zoom_amd64.deb
    dest: /tmp/zoom_amd64.deb
  tags:
    - desktop_zoom

- name: Install zoom package dependencies run 1
  apt:
    name:
      - libglib2.0-0
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb-randr0
      - libxcb-image0
      - libfontconfig1
      - libgl1-mesa-glx
      - libegl1-mesa
      - libxi6
      - libsm6
      - libxrender1
      - libpulse0
      - libxcomposite1
      - libxslt1.1
      - libsqlite3-0
      - libxcb-keysyms1
      - libxcb-xtest0
      - libdbus-1-3
      - libgstreamer-plugins-base1.0-0
      - dconf-cli
      - gir1.2-ibus-1.0
      - ibus
    state: latest
  tags:
    - desktop_zoom

- name: Install zoom
  command: dpkg -i /tmp/zoom_amd64.deb
  tags:
    - desktop_zoom
