---
# tasks file for desktop-teamviewer

- name: Configure the TeamViewer APT key
  apt_key: url=https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc state=present
  tags:
    - desktop_teamviewer

- name: Configure the Teamviewer APT repositories
  apt_repository: repo="deb http://linux.teamviewer.com/deb stable main" state=present
  tags:
    - desktop_teamviewer

- name: Update apt cache
  apt: update_cache=yes
  tags:
    - desktop_teamviewer

- name: Install Teamviewer
  apt: pkg=teamviewer state=present
  tags:
    - desktop_teamviewer
