---
galaxy_info:
  author: Jorge Medina
  description: Deploy fingerprint support on ubuntu desktop.
  company: KronOps
  license: MIT
  min_ansible_version: 2.4
  platforms:
  - name: Ubuntu
    versions:
    - focal
  categories:
  - destkop
dependencies: []
