---
# tasks file for desktop-oh-my-zsh

- name: Install dependencies for oh my zsh
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - zsh
    - git-core
  tags:
    - desktop_oh_my_zsh

- name: Deploy oh-my-zsh
  git: 
    repo: "{{ oh_my_zsh_repo }}"
    dest: "{{ oh_my_zsh_dir }}"
  become_user: "{{ item }}"
  with_items: "{{ oh_my_zsh_users }}"
  tags:
    - desktop_oh_my_zsh

- name: Create ~/.zshrc
  file:
    src: "{{ oh_my_zsh_dir }}/templates/zshrc.zsh-template"
    dest: "{{ oh_my_zsh_rc }}"
    state: link
  become_user: "{{ item }}"
  with_items: "{{ oh_my_zsh_users }}"
  tags:
    - desktop_oh_my_zsh

- name: Set zsh as default shell
  user: 
    name: "{{ item }}"
    shell: /bin/zsh
  with_items: "{{ oh_my_zsh_users }}"
  tags:
    - desktop_oh_my_zsh
