---
# tasks file for package-mgmt

- name: Remove unneeded packages to speed up Ansible on Ubuntu
  apt:
    name:
      - landscape-client
      - landscape-common
      - whoopsie
    state: absent
    purge: yes
  tags:
    - clean_package_mgmt

- name: Remove unattended upgrades packages to eliminate kernel conflicts and fill / space.
  apt:
    name:
      - unattended-upgrades
    state: absent
    purge: yes
  tags:
    - clean_package_mgmt

- name: Remove cron entries which use apt-get to update apt lists automatically
  lineinfile: dest=/etc/crontab regexp='apt-get' state=absent
  tags:
    - clean_package_mgmt

- name: Check if packages need to be autoremoved
  command: apt-get --dry-run autoremove
  register: check_autoremove
  changed_when: False
  tags:
    - clean_package_mgmt

- name: Autoremove unused packages
  command: apt-get -y autoremove
  when: "'packages will be REMOVED' in check_autoremove.stdout"
  tags:
    - clean_package_mgmt

- name: Check if packages need to be autocleaned
  command: apt-get --dry-run autoclean
  register: check_autoclean
  changed_when: False
  tags:
    - clean_package_mgmt

- name: Clean up package cache
  command: apt-get -y autoclean
  when: "'Del' in check_autoclean.stdout"
  tags:
    - clean_package_mgmt

- name: Purge old kernel images packages
  shell: dpkg --list | grep 'linux-image' | awk '{ print $2 }' | sort -V | sed -n '/'"$(uname -r | sed "s/\([0-9.-]*\)-\([^0-9]\+\)/\1/")"'/q;p' |sort -r | tail -n +3 | xargs sudo apt-get -y purge
  ignore_errors: True
  changed_when: False
  tags:
    - purge_package_mgmt

- name: Purge old kernel extra images packaes
  shell: dpkg --list | grep 'linux-image-extra' | awk '{ print $2 }' | sort -V | sed -n '/'"$(uname -r | sed "s/\([0-9.-]*\)-\([^0-9]\+\)/\1/")"'/q;p' |sort -r | tail -n +3 | xargs sudo apt-get -y purge
  ignore_errors: True
  changed_when: False
  tags:
    - purge_package_mgmt

- name: Purge old kernel header packaes
  shell: dpkg --list | grep 'linux-headers' | awk '{ print $2 }' | sort -V | sed -n '/'"$(uname -r | sed "s/\([0-9.-]*\)-\([^0-9]\+\)/\1/")"'/q;p' |sort -r | tail -n +3 | xargs sudo apt-get -y purge
  ignore_errors: True
  changed_when: False
  tags:
    - purge_package_mgmt

- name: Setting up apt MX official repositories for Ubuntu bionic
  copy: src=apt/bionic.sources.list.mx dest=/etc/apt/sources.list owner=root group=root mode=0644
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic'
  tags:
    - reposetup_package_mgmt

- name: Update apt cache lists
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - reposetup_package_mgmt

#- name: Setting up apt local settins
 #copy: src=apt/50tmpremount dest=/etc/apt/apt.conf.d/50tmpremount owner=root group=root mode=0644
 #copy: src=apt/88apt-proxy dest=/etc/apt/apt.conf.d/88apt-proxy owner=root group=root mode=0644
 #tags:
 #  - package_mgmt
